/**
 * Card image helpers. Uses cardImageManifest.json (generated by scripts/list-card-images.js)
 * from public/cards/pokemon and public/cards/onepiece. Add images there and run the script
 * to auto-detect.
 */

import manifest from './cardImageManifest.json';

export type CardTheme = 'pokemon' | 'onepiece';

const manifestTyped = manifest as { pokemon: string[]; onepiece: string[] };

export function getRandomCardImageUrl(theme: CardTheme): string {
  const list = manifestTyped[theme] ?? [];
  if (list.length === 0) return '';
  return list[Math.floor(Math.random() * list.length)];
}

export function getCardImageList(theme: CardTheme): string[] {
  return manifestTyped[theme] ?? [];
}
